version: '3.4'

services:
  busca:
    image: projetobusca
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./data:/app/Data
    networks:
      - projeto_network

networks:
  busca_network:
    driver: bridge
